export const actionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    ADD_SELECTED_PRODUCT: "ADD_SELECTED_PRODUCT",
    REMOVE_ALL_PRODUCTS: "REMOVE_ALL_PRODUCTS"
}